import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";

const outDir = join(process.cwd(), "dist", "client");
const manifest = JSON.parse(await readFile(join(outDir, ".vite", "manifest.json"), "utf8"));
const entry = manifest["src/entry-client.tsx"];
if (!entry?.file) throw new Error("SolidStart client entry is missing from the Vite manifest.");

const assets = Object.values(manifest)
  .flatMap((item) => item.css ?? [])
  .map((file) => `<link rel="stylesheet" href="/${file}" />`)
  .join("");
const html = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#17212b" />
  <meta name="description" content="口述历史转写与标注编辑器" />
  <link rel="icon" href="data:," />
  <title>口述历史转写与标注编辑器</title>
  ${assets}
  <link rel="modulepreload" href="/${entry.file}" />
</head>
<body>
  <div id="app"></div>
  <script type="module" src="/${entry.file}"></script>
</body>
</html>`;
await mkdir(outDir, { recursive: true });
await writeFile(join(outDir, "index.html"), html);

// --- Service worker with a fully enumerated precache manifest -------------
async function walk(dir) {
  const entries = [];
  for (const name of await readdir(dir)) {
    const full = join(dir, name);
    if (name === ".vite") continue;
    const info = await stat(full);
    if (info.isDirectory()) entries.push(...await walk(full));
    else entries.push(full);
  }
  return entries;
}

const files = await walk(outDir);
const precache = [];
for (const file of files) {
  const url = "/" + relative(outDir, file).split("\\").join("/");
  if (url === "/sw.js") continue;
  const buffer = await readFile(file);
  const revision = createHash("sha256").update(buffer).digest("hex").slice(0, 16);
  precache.push({ url, revision });
}
const version = createHash("sha256")
  .update(precache.map((item) => `${item.url}:${item.revision}`).join("|"))
  .digest("hex")
  .slice(0, 12);

// Precache entries are embedded at build time; keep the worker source free
// of any template-literal interpolation beyond this JSON payload.
const swSource = `// Generated by scripts/emit-static.mjs — do not edit.
const CACHE_NAME = "sologsb-1007-${version}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const SHELL_URL = "/index.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(PRECACHE.map((entry) => entry.url)).then(() => self.skipWaiting()),
    ),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;
  const url = new URL(request.url);

  // Hashed build assets are immutable: cache first, they are replaced on
  // deploy via a new precache version.
  if (url.pathname.startsWith("/_build/")) {
    event.respondWith(
      caches.match(request).then((cached) =>
        cached ||
        fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
      ),
    );
    return;
  }

  // Navigations: serve the cached app shell when the network is gone so a
  // basement refresh re-enters the editor instead of a white screen.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(SHELL_URL, copy));
          return response;
        })
        .catch(() => caches.match(SHELL_URL).then((shell) => shell || caches.match("/"))),
    );
    return;
  }

  // Everything else same-origin: stale-while-revalidate with offline fallback.
  event.respondWith(
    caches.match(request).then((cached) => {
      const network = fetch(request)
        .then((response) => {
          if (response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => cached);
      return cached || network;
    }),
  );
});
`;

await writeFile(join(outDir, "sw.js"), swSource);
console.log(`[solid-start] generated ${join(outDir, "index.html")}`);
console.log(`[service-worker] precached ${precache.length} files (version ${version})`);
